import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8'),source=read('business.js');
const live=source.slice(source.indexOf('let businessLiveChannel='),source.indexOf("$('#refreshBusinessLive').addEventListener"));
function setup(){const callbacks=[],removed=[],timers=[],nodes=new Map();let refreshed=0;
const context=vm.createContext({state:{workspace:{id:'one'},session:{user:{id:'u'}},locked:false,reportSnapshot:null},supabase:{channel:name=>{const channel={name,on(type,filter,callback){callbacks.push({filter,callback});return channel;},subscribe(callback){channel.status=callback;return channel;}};return channel;},removeChannel:channel=>removed.push(channel.name)},$:selector=>{if(!nodes.has(selector))nodes.set(selector,{textContent:'',classList:{add(){},remove(){}}});return nodes.get(selector);},$$:()=>[],window:{},navigator:{onLine:true},document:{hidden:false},setTimeout:(callback,delay)=>{timers.push({callback,delay});return timers.length;},clearTimeout(){},workspaceLoadSequence:1,brandingBusy:false,setupBusy:false,teamBusy:false,claimBusy:false,billBusy:false,incomeBusy:false,workflowBusy:false,billingBusy:false,reportExportBusy:false,setupOpen:false,businessAccessCheckBusy:false,renderReportAccess(){},refreshBusinessAccessState:async()=>{},selectBusinessWorkspace:async()=>{refreshed++;},businessBillingOwner:()=>false,refreshClaims:async()=>{},refreshBills:async()=>{},refreshBusinessTeam:async()=>{},query:async()=>[],renderBusinessBilling(){}});vm.runInContext(live,context);return {context,callbacks,removed,timers,refreshed:()=>refreshed};}
test('realtime subscribes only to neutral signals for the selected Business and disposes old channels',()=>{const f=setup();f.context.startBusinessRealtime();assert.equal(f.callbacks.length,2);assert.ok(f.callbacks.every(x=>x.filter.table==='business_change_signals'&&x.filter.filter==='workspace_id=eq.one'));f.context.state.workspace={id:'two'};f.context.workspaceLoadSequence=2;f.context.startBusinessRealtime();assert.equal(f.removed.length,1);f.callbacks[0].callback({new:{access_version:2,amount:999}});assert.equal(vm.runInContext('businessLivePending',f.context),false);});
test('access changes recheck permissions and reload access rather than consuming realtime records',async()=>{const f=setup();f.context.startBusinessRealtime();f.callbacks[0].callback({new:{access_version:2,amount:999}});await f.context.flushBusinessLiveRefresh();assert.equal(f.refreshed(),1);assert.equal(f.context.state.amount,undefined);});
test('data changes preserve open forms and defer refresh',async()=>{const f=setup();f.context.$$=()=>[{open:true}];f.context.queueBusinessLiveRefresh(false);await f.context.flushBusinessLiveRefresh();assert.equal(f.refreshed(),0);assert.equal(vm.runInContext('businessLivePending',f.context),true);assert.equal(f.timers.at(-1).delay,1500);});
test('a superseded access check cannot refresh another Business',async()=>{const f=setup();let resolve;f.context.refreshBusinessAccessState=()=>new Promise(r=>resolve=r);f.context.queueBusinessLiveRefresh(true);const request=f.context.flushBusinessLiveRefresh();f.context.stopBusinessRealtime();f.context.state.workspace={id:'two'};f.context.workspaceLoadSequence=2;resolve();await request;assert.equal(f.refreshed(),0);});
test('Team responses are fenced by workspace and load sequence',async()=>{const start=source.indexOf('async function refreshBusinessTeam()'),end=source.indexOf('\nasync function withTeamBusy',start);let resolve;const context=vm.createContext({state:{workspace:{id:'one'},locked:false,teamSnapshot:null},workspaceLoadSequence:1,query:()=>new Promise(r=>resolve=r),supabase:{rpc(){return{};}},renderTeam(){}});vm.runInContext(source.slice(start,end),context);const request=context.refreshBusinessTeam();context.state.workspace={id:'two'};context.workspaceLoadSequence=2;resolve({members:[{name:'Private first Business member'}]});await request;assert.equal(context.state.teamSnapshot,null);});
test('schema contains the exact Stage 12 migration',()=>assert.ok(read('supabase/schema.sql').includes(read('supabase/migrations/20260930130000_business_stage_12_realtime.sql'))));

test('an old expense save cannot close a new workspace form',async()=>{let resolve,closed=0,refreshed=0;const context=vm.createContext({state:{workspace:{id:'one'}},workspaceLoadSequence:1,claimBusy:false,$:()=>({value:'',close(){closed++;}}),query:()=>new Promise(r=>resolve=r),supabase:{rpc(){return{};}},refreshClaims:async()=>{refreshed++;},setClaimMessage(){},friendlyMessage:e=>e.message,openClaimDetail(){}});const a=source.indexOf('async function createClaim('),b=source.indexOf('\nfunction detailLine',a);vm.runInContext(source.slice(a,b),context);const request=context.createClaim({preventDefault(){}});context.workspaceLoadSequence=2;context.state.workspace={id:'two'};resolve({id:'old-claim'});await request;assert.equal(closed,0);assert.equal(refreshed,0);});
