-- Read-only prerequisite checks. Run before publishing the updated frontend.
with signatures as (
 select unnest(array['public.public_business_checkout_terms()',
 'public.submit_business_plan_request(uuid,text,integer,text,text,text,numeric,integer,text,date,text,text,text,text,text,bigint,uuid)',
 'public.review_subscription_payment(uuid,text,text)']) signature
), checks as (
 select 1 n,'Business release supports purchases and approved creation' check_name,
 public.product_customer_purchase_enabled('business') and public.product_customer_workspace_creation_enabled('business') ok
 union all select 2,'Checkout, submission and review RPCs exist',(select count(*)=3 from signatures where to_regprocedure(signature) is not null)
 union all select 3,'Protected RPCs are SECURITY DEFINER',(select count(*)=3 from signatures s join pg_proc p on p.oid=to_regprocedure(s.signature) where p.prosecdef)
 union all select 4,'Fixed RPC search paths',(select count(*)=3 from signatures s join pg_proc p on p.oid=to_regprocedure(s.signature) where array_to_string(p.proconfig,',') like '%search_path=public, pg_temp%')
 union all select 5,'Anonymous cannot execute protected RPCs',(select count(*)=3 from signatures where not has_function_privilege('anon',signature,'EXECUTE'))
 union all select 6,'Authenticated RPC grants exist',(select count(*)=3 from signatures where has_function_privilege('authenticated',signature,'EXECUTE'))
 union all select 7,'Purchase registry uses forced RLS',exists(select 1 from pg_class where oid=to_regclass('public.business_public_purchases') and relrowsecurity and relforcerowsecurity)
 union all select 8,'Provision permits use forced RLS',exists(select 1 from pg_class where oid=to_regclass('public.business_public_provision_permits') and relrowsecurity and relforcerowsecurity)
 union all select 9,'Customers cannot access the purchase registry',not has_table_privilege('authenticated','public.business_public_purchases','SELECT,INSERT,UPDATE,DELETE') and not has_table_privilege('anon','public.business_public_purchases','SELECT,INSERT,UPDATE,DELETE')
 union all select 10,'Customers cannot access provision permits',not has_table_privilege('authenticated','public.business_public_provision_permits','SELECT,INSERT,UPDATE,DELETE') and not has_table_privilege('anon','public.business_public_provision_permits','SELECT,INSERT,UPDATE,DELETE')
 union all select 11,'Provision helper stays private',not has_function_privilege('authenticated','public.business_public_provision_permit(uuid,uuid)','EXECUTE') and not has_function_privilege('anon','public.business_public_provision_permit(uuid,uuid)','EXECUTE')
 union all select 12,'Legacy review delegate stays private',not has_function_privilege('authenticated','public.review_subscription_payment_before_business_public(uuid,text,text)','EXECUTE') and not has_function_privilege('anon','public.review_subscription_payment_before_business_public(uuid,text,text)','EXECUTE')
 union all select 13,'Availability validates complete billing at commit',(select count(*)=2 from pg_trigger where tgname in ('validate_business_public_plan_trigger','validate_business_public_billing_trigger') and tgdeferrable and tginitdeferred and tgenabled='O')
 union all select 14,'Catalogue prices sync on availability and billing',(select count(*)=2 from pg_trigger where tgname in ('sync_business_public_plan_prices','sync_business_public_billing_prices') and tgenabled='O')
 union all select 15,'All available Business plans have valid billing',not exists(select 1 from public.plans where workspace_type='business' and available_for_purchase and (not is_active or not public.business_public_price_ready(id)))
 union all select 16,'Closed Business plans have no active public prices',not exists(select 1 from public.plans p join public.plan_prices x on x.plan_id=p.id where p.workspace_type='business' and (not p.available_for_purchase or not p.is_active) and x.is_active)
 union all select 17,'Published Business prices match canonical billing',not exists(select 1 from public.plans p join public.business_billing_settings b on b.plan_id=p.id cross join (values('monthly'),('annual')) c(period) where p.workspace_type='business' and p.is_active and p.available_for_purchase and (case when c.period='monthly' then b.monthly_base else b.annual_base end) is not null and not exists(select 1 from public.plan_prices x where x.plan_id=p.id and x.billing_period=c.period and x.is_active and x.currency=b.currency and x.amount=case when c.period='monthly' then b.monthly_base else b.annual_base end and x.extra_member_amount=case when c.period='monthly' then b.monthly_seat else b.annual_seat end and x.effective_from<=now() and (x.effective_until is null or x.effective_until>now())))
 union all select 18,'One pending public purchase per owner',exists(select 1 from pg_indexes where schemaname='public' and indexname='business_public_purchase_pending_owner_idx' and indexdef like '%UNIQUE%' and indexdef like '%pending_review%')
 union all select 19,'Workspace creation requires an exact approval permit',pg_get_functiondef(to_regprocedure('public.enforce_business_workspace_launch_control()')) like '%business_public_provision_permit(new.id,new.owner_id)%'
 union all select 20,'Public submission protects settings and duplicate retries',pg_get_functiondef(to_regprocedure('public.submit_business_plan_request(uuid,text,integer,text,text,text,numeric,integer,text,date,text,text,text,text,text,bigint,uuid)')) like '%BUSINESS_BILLING_SETTINGS_CHANGED%' and pg_get_functiondef(to_regprocedure('public.submit_business_plan_request(uuid,text,integer,text,text,text,numeric,integer,text,date,text,text,text,text,text,bigint,uuid)')) like '%p_submission_id%'
 union all select 21,'Payment review protects finance roles and self approval',pg_get_functiondef(to_regprocedure('public.review_subscription_payment(uuid,text,text)')) like '%FINANCE_REVIEW_ACCESS_REQUIRED%' and pg_get_functiondef(to_regprocedure('public.review_subscription_payment(uuid,text,text)')) like '%BUSINESS_BILLING_SELF_REVIEW_FORBIDDEN%'
 union all select 22,'Other subscription review paths keep their delegate',pg_get_functiondef(to_regprocedure('public.review_subscription_payment(uuid,text,text)')) like '%review_subscription_payment_before_business_public%'
 union all select 23,'Initial purchases appear in Business billing history',exists(select 1 from pg_constraint where conrelid='public.business_subscription_quotes'::regclass and conname='business_subscription_quotes_kind_check' and pg_get_constraintdef(oid) like '%purchase%')
 union all select 25,'Owner creation supports approved purchases without allowing owner edits',pg_get_functiondef(to_regprocedure('public.guard_business_owner_membership()')) like '%business_public_provision_permit(new.workspace_id,new.user_id)%' and pg_get_functiondef(to_regprocedure('public.guard_business_owner_membership()')) like '%BUSINESS_OWNERSHIP_PROCEDURE_REQUIRED%'
 union all select 24,'Legacy invite setup cannot bypass approved Business onboarding',pg_get_functiondef(to_regprocedure('public.enforce_business_admin_invitation_launch_control()')) like '%BUSINESS_MANUAL_GRANT_REQUIRED%'
)
select check_name,case when coalesce(ok,false) then 'PASS' else 'FAIL' end result from checks order by n;
